name: "global-trade-network"

x-type: "hlfv1"
x-loggingLevel: info

description: "The network to be in if you want to stay in the global trade business"

version: 1.0.0

client:

  organization: 21e09cb0c1de448adce8a513cee4b71eef3f6624

  logging:
    level: info

  peer:
    timeout:
      connection: 10s
      queryResponse: 45s
      executeTxResponse: 120s
  eventService:
    timeout:
      connection: 10s
      registrationResponse: 50s
  orderer:
    timeout:
      connection: 10s
      response: 45s

  cryptoconfig:
    path: /opt/gopath/src/github.com/hyperledger/fabric

  credentialStore:
    path: "/tmp/hfc-kvs"

    cryptoStore:
      path: /tmp/msp

    wallet: wallet-name

  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     ephemeral: false
     level: 256

channels:
  
  channeldemo:
    orderers:
      
      - orderer-83635d256b439bda0948c9db2fdab8334942be58-0.orderer-83635d256b439bda0948c9db2fdab8334942be58.default.svc.cluster.local
      
    peers:
      
      peer-21e09cb0c1de448adce8a513cee4b71eef3f6624-0.peer-21e09cb0c1de448adce8a513cee4b71eef3f6624.default.svc.cluster.local:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      
    chaincodes:
      - chaincode:2.1
  
organizations:
  
  21e09cb0c1de448adce8a513cee4b71eef3f6624:
    mspid: 21e09cb0c1de448adce8a513cee4b71eef3f6624MSP

    cryptoPath:  /Users/eagle/JavaSDKDemo-master/config/21e09cb0c1de448adce8a513cee4b71eef3f6624.peer/msp
    tlsCryptoKeyPath: /Users/eagle/JavaSDKDemo-master/config/21e09cb0c1de448adce8a513cee4b71eef3f6624.peer/tls/server.key
    tlsCryptoCertPath: /Users/eagle/JavaSDKDemo-master/config/21e09cb0c1de448adce8a513cee4b71eef3f6624.peer/tls/server.crt

    peers:
      
      - peer-21e09cb0c1de448adce8a513cee4b71eef3f6624-0.peer-21e09cb0c1de448adce8a513cee4b71eef3f6624.default.svc.cluster.local
      
    certificateAuthorities:
      - ca-org1
  
  ordererorg:
      mspID: "83635d256b439bda0948c9db2fdab8334942be58MSP"

      cryptoPath: /Users/eagle/JavaSDKDemo-master/config/83635d256b439bda0948c9db2fdab8334942be58.orderer/msp
orderer-eip: 49.4.87.203
orderers:
  
  orderer-83635d256b439bda0948c9db2fdab8334942be58-0.orderer-83635d256b439bda0948c9db2fdab8334942be58.default.svc.cluster.local:
    url: grpcs://49.4.87.203:30805

    grpcOptions:
      ssl-target-name-override: orderer-83635d256b439bda0948c9db2fdab8334942be58-0.orderer-83635d256b439bda0948c9db2fdab8334942be58.default.svc.cluster.local
      grpc-max-send-message-length: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: orderer-83635d256b439bda0948c9db2fdab8334942be58-0.orderer-83635d256b439bda0948c9db2fdab8334942be58.default.svc.cluster.local

    tlsCACerts:
      path: /Users/eagle/JavaSDKDemo-master/config/83635d256b439bda0948c9db2fdab8334942be58.orderer/msp/tlscacerts/tlsca.83635d256b439bda0948c9db2fdab8334942be58-cert.pem
  
peer-eip: 49.4.87.203
peers:
  
  peer-21e09cb0c1de448adce8a513cee4b71eef3f6624-0.peer-21e09cb0c1de448adce8a513cee4b71eef3f6624.default.svc.cluster.local:
    url: grpcs://49.4.87.203:30605

    eventUrl: grpcs://49.4.87.203:30705

    grpcOptions:
      ssl-target-name-override: peer-21e09cb0c1de448adce8a513cee4b71eef3f6624-0.peer-21e09cb0c1de448adce8a513cee4b71eef3f6624.default.svc.cluster.local
      grpc.http2.keepalive_time: 15
      sslProvider: openSSL
      negotiationType: TLS
      hostnameOverride: peer-21e09cb0c1de448adce8a513cee4b71eef3f6624-0.peer-21e09cb0c1de448adce8a513cee4b71eef3f6624.default.svc.cluster.local

    tlsCACerts:
      path: /Users/eagle/JavaSDKDemo-master/config/21e09cb0c1de448adce8a513cee4b71eef3f6624.peer/msp/tlscacerts/tlsca.21e09cb0c1de448adce8a513cee4b71eef3f6624-cert.pem
  
certificateAuthorities:
  ca-org1:
    url: https://ca_peerOrg1:7054
    httpOptions:
      verify: true
    tlsCACerts:
      path: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/ca_root.pem
      client:
       keyfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client-key.pem
       certfile: $GOPATH/src/github.com/hyperledger/fabric-sdk-go/test/api-server/tls/fabricca/certs/client/client_fabric_client.pem

    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca-org1